<a href="https://colab.research.google.com/github/JonaBaron/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# I am covering the the tensorflow fundamentals in this notebook!



*   Intro to tensors
*   Getting info from tensors
*   Manipulating tensors
*   Tensors & NumPy
*   Using @tf.function
*   Using GPUs with TensorFlow or TPUs



#Intro

In [ ]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
# Create a scalar tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of this tensor
scalar.ndim

0

In [ ]:
# Create a vector tensor with tf.constant()
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the number of dimensions of this tensor
vector.ndim

1

In [ ]:
# Create a matrix tensor with tf.constant()
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the number of dimensions of this tensor
matrix.ndim

2