<a href="https://colab.research.google.com/github/JonaBaron/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# I am covering the the tensorflow fundamentals in this notebook!



*   Intro to tensors
*   Getting info from tensors
*   Manipulating tensors
*   Tensors & NumPy
*   Using @tf.function
*   Using GPUs with TensorFlow or TPUs



#Intro

### Creating tensors with tf.constant

In [90]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [91]:
# Create a scalar tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [92]:
# Check the number of dimensions of this scalar
scalar.ndim

0

In [93]:
# Create a vector tensor with tf.constant()
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [94]:
# Check the number of dimensions of this vector
vector.ndim

1

In [95]:
# Create a matrix tensor with tf.constant()
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [96]:
# Check the number of dimensions of this matrix
matrix.ndim

2

In [97]:
# Creating another matrix
another_matrix = tf.constant([
                              [10., 2.],
                              [7., 2.],
                              [8., 9.]
                              ],dtype = tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [ 7.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [98]:
# Check the number of dimensions of this other matrix
another_matrix.ndim

2

In [99]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [100]:
# Check the number of dimensions of this tensor
tensor.ndim

3

I have created so far:

* Scalar: a single number
* Vector: a number with direction & magnitude
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

###Creating tensors with tf.variable

In [101]:
# Create the same tensor with tf.variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor= tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [102]:
# Let's try to change one element in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Try with .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some arbitary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))


# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                             [3, 4],
                             [2, 5]])

tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
not_shuffled